// src/components/form/SelectInput.jsx
import { forwardRef } from "react";
import mergeClass from "~/lib/mergeClass";

/**
 * @typedef {Object} SelectOption
 * @property {string} label -- yang akan tampil pada option select
 * @property {string} value -- value yang akan diproses saat option dipilih
*/

/**
 * @typedef {object} SelectInputProps
 *
 * @prop {string} 			[label] 		- text yang muncul di atas input
 * @prop {string} 			[helper] 		- text bantuan yang muncul di atas kanan input
 * @prop {string} 			[placeholder] 	- placeholder jika tidak ada option yang terpilih
 * @prop {string} 			[value] 		- value yang terpilih dari option yang tersedia
 * @prop {string} 			[error] 		- text merah yang muncul di bawah input
 * @prop {string} 			[inputClass] 	- html class untuk tag input
 * @prop {string} 			[className] 	- html class untuk wrapper
 * @prop {SelectOption[]} 	[options] 		- pilihan yang akan ditampilkan
 */

/**
 * @memberof 	Component.Form
 * @alias 		SelectInput
 *
 * @param {SelectInputProps & React.SelectHTMLAttributes<HTMLSelectElement>} props
 * @param {React.RefObject} ref
 *
 * @example
 * // select option
 * const myOptions = [
 * 	{ value: "1", label: "Banana" },
 * 	{ value: "2", label: "Papaya" },
 * 	{ value: "3", label: "Apple" },
 * ]
 *
 * // basic usage
 * <SelectInput label="Pilih buah" options={myOptions} />
 *
 * // different color
 * <SelectInput label="Pilih buah" options={myOptions} className="select-success" />
 *
 * // Untuk styling lebih lengkap bisa dilihat di [DaisyUI]{@link https://daisyui.com/components/select/}
 */
function SelectInput ({
	label = '',
	helper = '',
	placeholder = '',
	error = '',
	inputClass = '',
	className = '',
	options = [],
	...restProps
}, ref) {
	return <>
		<label className={mergeClass("form-control max-w-full w-full", className)}>
			{!!label
				? <div className="label">
					<span className="label-text">
						{label}
					</span>
					<span className="label-text-alt">
						{helper}
					</span>
				</div>
				: null}

			<select
				ref={ref}
				className={mergeClass(
					"select select-bordered w-full",
					inputClass,
					!!error ? "select-error" : ""
				)}
				{...restProps}
			>
				{!!placeholder
					? <option value="">{placeholder}</option>
					: null}

				{options.map(optionItem =>
					<option value={optionItem.value}>
						{optionItem.label}
					</option>
				)}
			</select>

			{!!error
				? <div className="label">
					<span className="label-text-alt text-error">
						{error}
					</span>
				</div>
				: null}
		</label>
	</>
}

const refForwardedSelectInput = forwardRef(SelectInput)

export default refForwardedSelectInput

// old_src/old_components/form/SelectInput.svelte
<script>
    import mergeClass from "~/lib/mergeClass";

	/**
	 * @typedef {Object} SelectOption
	 * @property {string} label -- yang akan tampil pada option select
	 * @property {string} value -- value yang akan diproses saat option dipilih
	*/

	/** @type {string} */ export let label = ''
	/** @type {string} */ export let helper = ''
	/** @type {string} */ export let value = ''
	/** @type {string} */ export let error = ''
	/** @type {string} */ export let placeholder = ''
	/** @type {string} */ export let inputClass = ''
	/** @type {SelectOption[]} */ export let options = []

	const { class: classProps, ...restProps } = $$restProps
</script>

<label class={mergeClass("form-control max-w-full w-full", classProps)}>
	{#if !!label}
		<div class="label">
			<span class="label-text">
				{label}
			</span>
			<span class="label-text-alt">
				{helper}
			</span>
		</div>
	{/if}

	<select
		on:change
		bind:value
		class={mergeClass(
			"select select-bordered w-full",
			inputClass,
			!!error ? "select-error" : ""
		)}
		{...restProps}
	>
		{#if !!placeholder}
			<option value="">{placeholder}</option>
		{/if}
		{#each options as optionItem (optionItem.value)}
			<option value={optionItem.value}>
				{optionItem.label}
			</option>
		{/each}
	</select>

	{#if !!error}
		<div class="label">
			<span class="label-text-alt text-error">
				{error}
			</span>
		</div>
	{/if}
</label>
